import type { AgentProvider } from "./llm-provider-interface.js";
import type { AgentTaskSpec, AgentTaskOutput, AgentPatchOp } from "../agent-task.js";

/**
 * Deterministic provider used for tests and the V1 prototype path. It never
 * calls a network or LLM — it derives a structured patch from the spec's
 * action + IR fragment. The output is always re-validated by the orchestrator
 * against the spec, so this provider has no special privileges.
 *
 * The body content is intentionally simple and deterministic: it materializes
 * a placeholder file that carries the artifact id and the entity ids the task
 * is scoped to, so acceptance criteria like `string_present` can be checked.
 */
export class DeterministicProvider implements AgentProvider {
  readonly id = "deterministic";
  readonly enabled = true;

  async run(spec: AgentTaskSpec): Promise<AgentTaskOutput> {
    return {
      schema_version: "arch.agent.output.v1",
      task_id: spec.task_id,
      action_id: spec.action_id,
      artifact_id: spec.artifact_id,
      patches: [buildPatch(spec)],
      satisfied_criteria: spec.acceptance_criteria.map((c) => c.id),
      notes: `deterministic ${spec.role} patch for ${spec.artifact_id}`,
    };
  }
}

/** Map the planned action kind to a single structured patch op. */
function buildPatch(spec: AgentTaskSpec): AgentPatchOp {
  const content = renderDeterministicBody(spec);
  switch (spec.action.kind) {
    case "write_extension_stub":
      return { kind: "write_extension_stub", path: spec.action.path, content };
    case "create_file":
      return { kind: "create_file", path: spec.action.path, content };
    case "delete_file":
      return { kind: "delete_file", path: spec.action.path };
    case "patch_generated_region":
      return {
        kind: "patch_generated_region",
        path: spec.action.path,
        region_marker_id: spec.action.region_marker_id ?? "arch:region",
        content,
      };
    default:
      return { kind: "rewrite_whole_file", path: spec.action.path, content };
  }
}

function renderDeterministicBody(spec: AgentTaskSpec): string {
  return [
    `// Generated by Arch (${spec.role} agent, deterministic provider).`,
    `// Artifact: ${spec.artifact_id}`,
    `// Entities: ${spec.entity_ids.join(", ")}`,
    `// Intent: ${spec.intent_summary}`,
    "",
  ].join("\n");
}
