import { describe, expect, it } from "vitest";
import type { CanonicalIR } from "@arch/ir";
import { generate } from "../../generator.js";

function fixtureIR(): CanonicalIR {
  return {
    schema_version: "arch.ir.v1",
    canonical_hash: "deadbeef",
    target: { stack: "ts.node.fastify.postgres.prisma", cache: "redis" },
    models: [
      {
        id: "model:Post",
        kind: "model",
        name: "Post",
        fields: [
          { id: "field:Post.id", kind: "field", name: "id", model_id: "model:Post", type: { kind: "id" }, nullable: false, indexed: false },
          { id: "field:Post.body", kind: "field", name: "body", model_id: "model:Post", type: { kind: "primitive", name: "string" }, nullable: false, indexed: false },
        ],
        indexes: [],
      },
    ],
    integrations: [
      { id: "integration:PushNotifier", kind: "integration", name: "PushNotifier", properties: { kind: "webhook", failure: "best_effort" } },
    ],
    policies: [
      { id: "policy:sanitizeHtml", kind: "policy", name: "sanitizeHtml", body: "strip script tags" },
    ],
    workflows: [
      {
        id: "workflow:CreatePost",
        kind: "workflow",
        name: "CreatePost",
        trigger: { kind: "api", method: "POST", path: "/posts", auth: "none" },
        steps: [
          { id: "step:CreatePost.0.validate", kind: "workflow_step", name: "CreatePost.0.validate", workflow_id: "workflow:CreatePost", order: 0, operation: { kind: "validate", target: "body" } },
          { id: "step:CreatePost.1.sanitize", kind: "workflow_step", name: "CreatePost.1.sanitize", workflow_id: "workflow:CreatePost", order: 1, operation: { kind: "sanitize", target: "body", policy_id: "policy:sanitizeHtml" } },
          { id: "step:CreatePost.2.insert", kind: "workflow_step", name: "CreatePost.2.insert", workflow_id: "workflow:CreatePost", order: 2, operation: { kind: "insert", model_id: "model:Post" } },
          { id: "step:CreatePost.3.call", kind: "workflow_step", name: "CreatePost.3.call", workflow_id: "workflow:CreatePost", order: 3, operation: { kind: "call", integration_id: "integration:PushNotifier", operation: "send" } },
        ],
        guarantees: [
          { id: "guarantee:CreatePost.no_unsanitized_html_persisted", kind: "guarantee", name: "no_unsanitized_html_persisted", workflow_id: "workflow:CreatePost", form: "short", arguments: {} },
          { id: "guarantee:CreatePost.notification_failure_does_not_rollback_post", kind: "guarantee", name: "notification_failure_does_not_rollback_post", workflow_id: "workflow:CreatePost", form: "short", arguments: {} },
          { id: "guarantee:CreatePost.post_creation_p95_latency", kind: "guarantee", name: "post_creation_p95_latency", workflow_id: "workflow:CreatePost", form: "short", arguments: { limit_ms: 250 } },
        ],
      },
    ],
    customs: [],
    artifacts: [],
    ownership: [],
    verification: { typecheck: true, tests: true, migrations: true },
    guarantee_coverage: [],
    source_locations: [],
  };
}

describe("generator headers", () => {
  const ir = fixtureIR();
  const result = generate(ir);

  it("emits at least one file per major artifact category", () => {
    const paths = result.files.map((f) => f.path);
    expect(paths).toContain("package.json");
    expect(paths).toContain("tsconfig.json");
    expect(paths).toContain("vitest.config.ts");
    expect(paths).toContain("docker-compose.yml");
    expect(paths).toContain("prisma/schema.prisma");
    expect(paths).toContain("src/runtime/config.ts");
    expect(paths).toContain("src/runtime/db.ts");
    expect(paths).toContain("src/runtime/cache.ts");
    expect(paths).toContain("src/runtime/auth.ts");
    expect(paths).toContain("src/app.ts");
    expect(paths).toContain("src/server.ts");
    expect(paths).toContain("src/models/Post.ts");
    expect(paths).toContain("src/validators/Post.ts");
    expect(paths).toContain("src/workflows/CreatePost.ts");
    expect(paths).toContain("src/routes/CreatePost.ts");
    expect(paths).toContain("src/policies/sanitizeHtml.ts");
    expect(paths).toContain("src/integrations/PushNotifier.ts");
  });

  it("every generated file carries the required header", () => {
    const has = (content: string, key: string, value: string): boolean =>
      content.includes(`${key}: ${value}`) || content.includes(`"${key}": ${JSON.stringify(value)}`);
    for (const f of result.files) {
      expect(f.content, `file=${f.path}`).toContain("Generated by Arch");
      expect(has(f.content, "artifact_id", f.artifact_id), `file=${f.path}`).toBe(true);
      expect(has(f.content, "ownership_kind", f.ownership_kind), `file=${f.path}`).toBe(true);
      expect(has(f.content, "write_scope", f.write_scope), `file=${f.path}`).toBe(true);
      expect(has(f.content, "generator_id", f.generator_id), `file=${f.path}`).toBe(true);
      expect(has(f.content, "ir_fragment_hash", f.ir_fragment_hash), `file=${f.path}`).toBe(true);
      for (const eid of f.entity_ids) {
        expect(f.content, `file=${f.path} entity=${eid}`).toContain(eid);
      }
    }
  });

  it("integration files are stub_only and live under src/integrations", () => {
    const stubs = result.files.filter((f) => f.path.startsWith("src/integrations/"));
    expect(stubs.length).toBeGreaterThan(0);
    for (const f of stubs) {
      expect(f.stub_only, `file=${f.path}`).toBe(true);
      expect(f.ownership_kind, `file=${f.path}`).toBe("extension_point");
      expect(f.write_scope, `file=${f.path}`).toBe("stub_only");
      expect(f.content).toContain("stub_only: true");
    }
  });

  it("uses spec-compliant ownership vocabulary (whole_file / stub_only)", () => {
    for (const f of result.files) {
      if (f.ownership_kind === "generated_file") {
        expect(f.write_scope, `file=${f.path}`).toBe("whole_file");
      } else {
        expect(f.ownership_kind, `file=${f.path}`).toBe("extension_point");
        expect(f.write_scope, `file=${f.path}`).toBe("stub_only");
      }
      // legacy vocabulary must be gone
      expect(["arch_only", "human_only", "shared"]).not.toContain(f.write_scope);
    }
  });

  it("emits the html-safety and notification-nonrollback guarantee tests", () => {
    const paths = result.files.map((f) => f.path);
    expect(paths).toContain("tests/guarantees/no_unsanitized_html_persisted.CreatePost.test.ts");
    expect(paths).toContain("tests/guarantees/notification_failure_does_not_rollback_post.CreatePost.test.ts");
    expect(paths).toContain("tests/guarantees/post_creation_p95_latency.CreatePost.test.ts");
  });

  it("html-safety guarantee test asserts script-tag stripping", () => {
    const test = result.files.find((f) => f.path === "tests/guarantees/no_unsanitized_html_persisted.CreatePost.test.ts");
    expect(test).toBeTruthy();
    expect(test!.content).toMatch(/<script/);
    expect(test!.content).toMatch(/onerror/i);
    expect(test!.content).toMatch(/not\.toMatch/);
  });

  it("notification-nonrollback guarantee test mocks PushNotifier failure", () => {
    const test = result.files.find((f) => f.path === "tests/guarantees/notification_failure_does_not_rollback_post.CreatePost.test.ts");
    expect(test).toBeTruthy();
    expect(test!.content).toMatch(/spyOn\(PushNotifier/);
    expect(test!.content).toMatch(/throw new Error/);
    expect(test!.content).toMatch(/rows\.length\)\.toBe\(1\)/);
  });

  it("generated content is independent of source_location_id (no false drift after unrelated edits)", () => {
    const base = fixtureIR();
    const withSrcA = JSON.parse(JSON.stringify(base)) as CanonicalIR;
    (withSrcA.policies[0] as { source_location_id?: string }).source_location_id = "src:3";
    (withSrcA.models[0] as { source_location_id?: string }).source_location_id = "src:5";
    const withSrcB = JSON.parse(JSON.stringify(base)) as CanonicalIR;
    (withSrcB.policies[0] as { source_location_id?: string }).source_location_id = "src:99";
    (withSrcB.models[0] as { source_location_id?: string }).source_location_id = "src:42";

    const a = generate(withSrcA);
    const b = generate(withSrcB);
    for (const fa of a.files) {
      const fb = b.files.find((f) => f.path === fa.path)!;
      expect(fb.content, `file=${fa.path}`).toBe(fa.content);
      expect(fb.ir_fragment_hash, `hash ${fa.path}`).toBe(fa.ir_fragment_hash);
    }
  });

  it("output is deterministic (byte-identical across runs)", () => {
    const a = generate(ir);
    const b = generate(ir);
    expect(a.files.length).toBe(b.files.length);
    for (let i = 0; i < a.files.length; i++) {
      expect(a.files[i]!.path).toBe(b.files[i]!.path);
      expect(a.files[i]!.content).toBe(b.files[i]!.content);
      expect(a.files[i]!.ir_fragment_hash).toBe(b.files[i]!.ir_fragment_hash);
    }
  });

  it("file paths are sorted lexicographically", () => {
    const paths = result.files.map((f) => f.path);
    const sorted = [...paths].sort();
    expect(paths).toEqual(sorted);
  });

  it("custom/README.md is emitted as a stub-only marker", () => {
    const readme = result.files.find((f) => f.path === "src/custom/README.md");
    expect(readme).toBeTruthy();
    expect(readme!.stub_only).toBe(true);
    expect(readme!.write_scope).toBe("stub_only");
  });

  it("policy 'sanitizeHtml' template strips <script> tags and on* attrs", () => {
    const sanitizer = result.files.find((f) => f.path === "src/policies/sanitizeHtml.ts");
    expect(sanitizer).toBeTruthy();
    // Source uses two regex literals to handle <script>...</script> and <script ... />
    expect(sanitizer!.content).toMatch(/<script/);
    expect(sanitizer!.content).toMatch(/on\[a-z\]\+/i);
  });
});
