import { createHash } from "node:crypto";
import type { CanonicalIR, OwnershipKind, OwnershipWriteScope } from "@arch/ir";
import { renderPackageJson } from "./templates/package-json.js";
import { renderDockerCompose } from "./templates/docker-compose.js";
import { renderPrismaSchema } from "./templates/prisma-schema.js";
import { renderRuntimeConfig } from "./templates/runtime-config.js";
import { renderRuntimeDb } from "./templates/runtime-db.js";
import { renderRuntimeDbPrisma } from "./templates/runtime-db-prisma.js";
import { renderRuntimeCache } from "./templates/runtime-cache.js";
import { renderFastifyApp, renderFastifyServer } from "./templates/fastify-app.js";
import { renderModel } from "./templates/model.js";
import { renderValidator } from "./templates/validator.js";
import { renderRoute } from "./templates/route.js";
import { renderWorkflow } from "./templates/workflow.js";
import { renderPolicy } from "./templates/policy.js";
import { renderIntegrationStub } from "./templates/integration-stub.js";
import { renderCustomExtensionStub } from "./templates/custom-extension-stub.js";
import { renderModelTest } from "./templates/test-model.js";
import { renderWorkflowTest } from "./templates/test-workflow.js";
import { renderGuaranteeTests } from "./templates/test-guarantees.js";
import { camel, pascal } from "./naming.js";

export interface GeneratedFile {
  readonly path: string;
  readonly content: string;
  readonly artifact_id: string;
  readonly entity_ids: readonly string[];
  readonly ir_fragment_hash: string;
  readonly mode: "full_file" | "region";
  readonly write_scope: OwnershipWriteScope;
  readonly ownership_kind: OwnershipKind;
  readonly generator_id: string;
  readonly template_id?: string;
  readonly stub_only?: boolean;
}

export interface GeneratorResult {
  readonly files: readonly GeneratedFile[];
}

const GENERATOR_ID = "arch.generator.v1";
const HEADER_MARK = "Generated by Arch";

function fragmentHash(value: unknown): string {
  // Source positions are NOT semantic: an unrelated edit elsewhere in the
  // spec shifts line numbers but must not change generated content (otherwise
  // every unchanged file would falsely report drift). Strip source-location
  // fields before hashing, mirroring the canonical-IR hash.
  return createHash("sha256").update(stableStringify(stripSourceFields(value))).digest("hex");
}

function stripSourceFields(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stripSourceFields);
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      if (k === "source_location_id" || k === "source_locations") continue;
      out[k] = stripSourceFields(v);
    }
    return out;
  }
  return value;
}

function stableStringify(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (typeof value === "object") {
    const keys = Object.keys(value as Record<string, unknown>).sort();
    const body = keys
      .map((k) => `${JSON.stringify(k)}:${stableStringify((value as Record<string, unknown>)[k])}`)
      .join(",");
    return `{${body}}`;
  }
  return JSON.stringify(value);
}

export interface HeaderInfo {
  readonly artifactId: string;
  readonly entityIds: readonly string[];
  readonly ownershipKind: OwnershipKind;
  readonly writeScope: OwnershipWriteScope;
  readonly generatorId: string;
  readonly templateId: string;
  readonly irFragmentHash: string;
  readonly stubOnly?: boolean;
}

type CommentFlavor = "ts" | "prisma" | "yaml" | "md" | "json";

export function renderHeader(info: HeaderInfo, comment: CommentFlavor = "ts"): string {
  const lines = [
    HEADER_MARK,
    `artifact_id: ${info.artifactId}`,
    `entity_ids: [${info.entityIds.join(", ")}]`,
    `ownership_kind: ${info.ownershipKind}`,
    `write_scope: ${info.writeScope}`,
    `generator_id: ${info.generatorId}`,
    `template_id: ${info.templateId}`,
    `ir_fragment_hash: ${info.irFragmentHash}`,
  ];
  if (info.stubOnly) lines.push("stub_only: true");

  if (comment === "ts") {
    return ["/**", ...lines.map((l) => ` * ${l}`), " */", ""].join("\n");
  }
  if (comment === "prisma") {
    return [...lines.map((l) => `// ${l}`), ""].join("\n");
  }
  if (comment === "yaml") {
    return [...lines.map((l) => `# ${l}`), ""].join("\n");
  }
  if (comment === "md") {
    return [`<!-- ${HEADER_MARK} -->`, `<!-- artifact_id: ${info.artifactId} -->`, `<!-- entity_ids: [${info.entityIds.join(", ")}] -->`, `<!-- ownership_kind: ${info.ownershipKind} -->`, `<!-- write_scope: ${info.writeScope} -->`, `<!-- generator_id: ${info.generatorId} -->`, `<!-- template_id: ${info.templateId} -->`, `<!-- ir_fragment_hash: ${info.irFragmentHash} -->`, ""].join("\n");
  }
  return "";
}

export function jsonHeader(info: HeaderInfo): Record<string, unknown> {
  return {
    _arch: {
      generated_by: HEADER_MARK,
      artifact_id: info.artifactId,
      entity_ids: info.entityIds,
      ownership_kind: info.ownershipKind,
      write_scope: info.writeScope,
      generator_id: info.generatorId,
      template_id: info.templateId,
      ir_fragment_hash: info.irFragmentHash,
    },
  };
}

export interface BuildContext {
  readonly ir: CanonicalIR;
}

/**
 * Generate the entire backend project from canonical IR.
 * Output is deterministic: same IR (modulo non-semantic order) → byte-identical files.
 */
export function generate(ir: CanonicalIR): GeneratorResult {
  const files: GeneratedFile[] = [];
  const ctx: BuildContext = { ir };

  push(files, spec("package.json", "tmpl.package-json", "ts.package-json", []),
       renderPackageJson(ir), "json", ir);
  push(files, spec("tsconfig.json", "tmpl.tsconfig", "ts.tsconfig", []),
       renderTsconfig(), "json", ir);
  push(files, spec("vitest.config.ts", "tmpl.vitest-config", "ts.vitest-config", []),
       renderVitestConfig(), "ts", ir);
  push(files, spec("docker-compose.yml", "tmpl.docker-compose", "ts.docker-compose", []),
       renderDockerCompose(ir), "yaml", ir);
  push(files, spec("prisma/schema.prisma", "tmpl.prisma-schema", "ts.prisma-schema",
       ir.models.map((m) => m.id)), renderPrismaSchema(ir), "prisma", ir);

  push(files, spec("src/runtime/config.ts", "tmpl.runtime-config", "ts.runtime-config", []),
       renderRuntimeConfig(ir), "ts", ir);
  push(files, spec("src/runtime/db.ts", "tmpl.runtime-db", "ts.runtime-db",
       ir.models.map((m) => m.id)), renderRuntimeDb(ir), "ts", ir);
  push(files, spec("src/runtime/db-prisma.ts", "tmpl.runtime-db-prisma", "ts.runtime-db-prisma",
       ir.models.map((m) => m.id)), renderRuntimeDbPrisma(ir), "ts", ir);
  push(files, spec("src/runtime/cache.ts", "tmpl.runtime-cache", "ts.runtime-cache", []),
       renderRuntimeCache(ir), "ts", ir);
  push(files, spec("src/runtime/auth.ts", "tmpl.runtime-auth", "ts.runtime-auth", []),
       renderRuntimeAuth(), "ts", ir);

  push(files, spec("src/app.ts", "tmpl.fastify-app", "ts.fastify-app",
       ir.workflows.map((w) => w.id)), renderFastifyApp(ir), "ts", ir);
  push(files, spec("src/server.ts", "tmpl.fastify-server", "ts.fastify-server", []),
       renderFastifyServer(ir), "ts", ir);

  for (const m of ir.models) {
    push(files, spec(`src/models/${pascal(m.name)}.ts`, `tmpl.model.${m.name}`, "ts.model", [m.id]),
         renderModel(m), "ts", ir, m);
    push(files, spec(`src/validators/${pascal(m.name)}.ts`, `tmpl.validator.${m.name}`, "ts.validator", [m.id]),
         renderValidator(m), "ts", ir, m);
    push(files, spec(`tests/models/${pascal(m.name)}.test.ts`, `tmpl.model-test.${m.name}`, "ts.model-test", [m.id]),
         renderModelTest(m), "ts", ir, m);
  }

  for (const w of ir.workflows) {
    const wfEntities = [w.id, ...w.steps.map((s) => s.id), ...w.guarantees.map((g) => g.id)];
    push(files, spec(`src/workflows/${pascal(w.name)}.ts`, `tmpl.workflow.${w.name}`, "ts.workflow", wfEntities),
         renderWorkflow(w, ctx), "ts", ir, w);
    push(files, spec(`src/routes/${pascal(w.name)}.ts`, `tmpl.route.${w.name}`, "ts.route", [w.id]),
         renderRoute(w), "ts", ir, w);
    push(files, spec(`tests/workflows/${pascal(w.name)}.test.ts`, `tmpl.workflow-test.${w.name}`, "ts.workflow-test", wfEntities),
         renderWorkflowTest(w, ctx), "ts", ir, w);
    for (const file of renderGuaranteeTests(w, ctx)) {
      push(files, spec(file.path, `tmpl.guarantee-test.${w.name}.${file.path}`, "ts.guarantee-test", wfEntities),
           file.content, "ts", ir, w);
    }
  }

  for (const p of ir.policies) {
    push(files, spec(`src/policies/${camel(p.name)}.ts`, `tmpl.policy.${p.name}`, "ts.policy", [p.id]),
         renderPolicy(p), "ts", ir, p);
  }

  for (const ig of ir.integrations) {
    files.push(buildExtensionStub(
      `src/integrations/${pascal(ig.name)}.ts`,
      `tmpl.integration-stub.${ig.name}`,
      "ts.integration-stub",
      [ig.id],
      renderIntegrationStub(ig),
      ir, ig, "ts",
    ));
  }

  for (const c of ir.customs) {
    files.push(buildExtensionStub(
      `src/custom/${pascal(c.name)}.ts`,
      `tmpl.custom-stub.${c.name}`,
      "ts.custom-stub",
      [c.id],
      renderCustomExtensionStub(c),
      ir, c, "ts",
    ));
  }

  files.push(buildExtensionStub(
    "src/custom/README.md",
    "tmpl.custom-readme",
    "md.custom-readme",
    [],
    renderCustomReadme(),
    ir, null, "md",
  ));

  // Sort files by path to guarantee deterministic ordering across runs.
  files.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return { files };
}

interface FileSpec {
  readonly path: string;
  readonly artifactId: string;
  readonly templateId: string;
  readonly entityIds: readonly string[];
}

function spec(path: string, artifactId: string, templateId: string, entityIds: readonly string[]): FileSpec {
  return { path, artifactId, templateId, entityIds };
}

function push(
  out: GeneratedFile[],
  s: FileSpec,
  body: string,
  flavor: CommentFlavor,
  ir: CanonicalIR,
  fragmentSource?: unknown,
): void {
  const fHash = fragmentHash(fragmentSource ?? { artifact: s.artifactId, target: ir.target });
  const info: HeaderInfo = {
    artifactId: s.artifactId,
    entityIds: s.entityIds,
    ownershipKind: "generated_file",
    writeScope: "whole_file",
    generatorId: GENERATOR_ID,
    templateId: s.templateId,
    irFragmentHash: fHash,
  };

  let content: string;
  if (flavor === "json") {
    content = renderJsonWithHeader(info, body);
  } else {
    const header = renderHeader(info, flavor);
    content = `${header}${body}`;
    if (!content.endsWith("\n")) content += "\n";
  }

  out.push({
    path: s.path,
    content,
    artifact_id: s.artifactId,
    entity_ids: s.entityIds,
    ir_fragment_hash: fHash,
    mode: "full_file",
    write_scope: "whole_file",
    ownership_kind: "generated_file",
    generator_id: GENERATOR_ID,
    template_id: s.templateId,
  });
}

function buildExtensionStub(
  path: string,
  artifactId: string,
  templateId: string,
  entityIds: readonly string[],
  body: string,
  ir: CanonicalIR,
  fragmentSource: unknown,
  flavor: CommentFlavor,
): GeneratedFile {
  const fHash = fragmentHash(fragmentSource ?? { artifact: artifactId, target: ir.target });
  const info: HeaderInfo = {
    artifactId,
    entityIds,
    ownershipKind: "extension_point",
    writeScope: "stub_only",
    generatorId: GENERATOR_ID,
    templateId,
    irFragmentHash: fHash,
    stubOnly: true,
  };
  const header = renderHeader(info, flavor);
  let content = `${header}${body}`;
  if (!content.endsWith("\n")) content += "\n";
  return {
    path,
    content,
    artifact_id: artifactId,
    entity_ids: entityIds,
    ir_fragment_hash: fHash,
    mode: "full_file",
    write_scope: "stub_only",
    ownership_kind: "extension_point",
    generator_id: GENERATOR_ID,
    template_id: templateId,
    stub_only: true,
  };
}

function renderJsonWithHeader(info: HeaderInfo, body: string): string {
  const parsed = JSON.parse(body) as Record<string, unknown>;
  const merged = { ...jsonHeader(info), ...parsed };
  return `${JSON.stringify(merged, null, 2)}\n`;
}

function renderTsconfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      lib: ["ES2022"],
      strict: true,
      esModuleInterop: true,
      forceConsistentCasingInFileNames: true,
      skipLibCheck: true,
      resolveJsonModule: true,
      isolatedModules: true,
      declaration: false,
      sourceMap: false,
      outDir: "dist",
      rootDir: ".",
    },
    include: ["src/**/*.ts", "tests/**/*.ts"],
    exclude: ["node_modules", "dist"],
  }, null, 2);
}

function renderVitestConfig(): string {
  return [
    'import { defineConfig } from "vitest/config";',
    "",
    "export default defineConfig({",
    "  test: {",
    '    include: ["tests/**/*.test.ts"],',
    '    exclude: ["**/node_modules/**", "**/dist/**"],',
    '    environment: "node",',
    "  },",
    "});",
  ].join("\n");
}

function renderRuntimeAuth(): string {
  return [
    "/** Minimal request-auth helper. */",
    "export interface AuthContext {",
    "  readonly userId: string | null;",
    "}",
    "",
    "export function noAuth(): AuthContext {",
    "  return { userId: null };",
    "}",
    "",
    "export function requireAuth(headers: Record<string, string | undefined>): AuthContext {",
    '  const token = headers["authorization"];',
    '  if (!token) throw new Error("unauthenticated");',
    '  return { userId: token.replace(/^Bearer\\s+/i, "") };',
    "}",
  ].join("\n");
}

function renderCustomReadme(): string {
  return [
    "# Custom extensions",
    "",
    "Files in this directory are **stub-only**: Arch wrote them once, and",
    "will never overwrite your edits afterwards. Implement the declared",
    "contract for each extension here.",
    "",
  ].join("\n");
}
