/**
 * Drift detector tests — `arch check` AC3 (the third bullet).
 *
 * The detector MUST report:
 *   - `generated_file_modified` when a generated file's bytes differ from
 *     the recorded `content_hash`.
 *   - `generated_file_missing` when a recorded artifact has been deleted.
 *   - `missing_generated_test` when a generated test file under `tests/`
 *     has been deleted.
 *
 * Each entry MUST carry the artifact_id and entity_ids for downstream
 * tooling.
 */

import { createHash } from "node:crypto";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { detectDrift } from "../src/drift-detector.js";
import { DriftMetadataError } from "../src/errors.js";

function sha256(s: string): string {
  return createHash("sha256").update(s).digest("hex");
}

async function writeFileEnsuringDir(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents, "utf8");
}

describe("drift detector", () => {
  let tmp: string;
  let metaDir: string;
  let projectRoot: string;

  beforeEach(async () => {
    tmp = await mkdtemp(resolve(tmpdir(), "arch-drift-"));
    projectRoot = resolve(tmp, "project");
    metaDir = resolve(projectRoot, ".arch");
    await mkdir(metaDir, { recursive: true });
  });

  afterEach(async () => {
    // Best effort: tmp dirs are small, no-op if cleanup fails.
  });

  it("fails closed when artifact-map.json is absent", async () => {
    await expect(detectDrift(metaDir, projectRoot)).rejects.toBeInstanceOf(
      DriftMetadataError,
    );
  });

  it("fails closed when ownership.json is absent", async () => {
    await writeFile(resolve(metaDir, "artifact-map.json"), JSON.stringify({ entries: [] }));
    await expect(detectDrift(metaDir, projectRoot)).rejects.toBeInstanceOf(
      DriftMetadataError,
    );
  });

  it("fails closed when metadata JSON is corrupt", async () => {
    await writeFile(resolve(metaDir, "artifact-map.json"), "{not-json");
    await writeFile(resolve(metaDir, "ownership.json"), JSON.stringify({ entries: [] }));
    await expect(detectDrift(metaDir, projectRoot)).rejects.toBeInstanceOf(
      DriftMetadataError,
    );
  });

  it("reports generated_file_modified when bytes diverge from content_hash", async () => {
    const contents = "// generated by arch v1\n";
    const expectedHash = sha256(contents);
    const onDisk = "// HUMAN HAND-EDIT\n";

    const filePath = resolve(projectRoot, "src/generated/models/post.ts");
    await writeFileEnsuringDir(filePath, onDisk);

    await writeFile(
      resolve(metaDir, "artifact-map.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:src/generated/models/post.ts",
            path: "src/generated/models/post.ts",
            entity_ids: ["model:Post"],
          },
        ],
      }),
    );
    await writeFile(
      resolve(metaDir, "ownership.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:src/generated/models/post.ts",
            ownership_kind: "generated_file",
            write_scope: "whole_file",
            content_hash: expectedHash,
          },
        ],
      }),
    );

    const report = await detectDrift(metaDir, projectRoot);
    expect(report.entries.length).toBe(1);
    const e = report.entries[0]!;
    expect(e.kind).toBe("generated_file_modified");
    expect(e.artifact_id).toBe("artifact:src/generated/models/post.ts");
    expect(e.entity_ids).toEqual(["model:Post"]);
    expect(e.expected_hash).toBe(expectedHash);
    expect(e.actual_hash).toBe(sha256(onDisk));
    expect(e.message).toContain("modified");
    expect(e.message).toContain("model:Post");
  });

  it("reports generated_file_missing for a deleted, non-test artifact", async () => {
    await writeFile(
      resolve(metaDir, "artifact-map.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:src/generated/routes/posts.ts",
            path: "src/generated/routes/posts.ts",
            entity_ids: ["workflow:CreatePost"],
          },
        ],
      }),
    );
    await writeFile(
      resolve(metaDir, "ownership.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:src/generated/routes/posts.ts",
            ownership_kind: "generated_file",
            write_scope: "whole_file",
            content_hash: sha256("ghost"),
          },
        ],
      }),
    );

    const report = await detectDrift(metaDir, projectRoot);
    expect(report.entries.length).toBe(1);
    const e = report.entries[0]!;
    expect(e.kind).toBe("generated_file_missing");
    expect(e.artifact_id).toBe("artifact:src/generated/routes/posts.ts");
    expect(e.entity_ids).toEqual(["workflow:CreatePost"]);
  });

  it("reports missing_generated_test for a deleted test artifact", async () => {
    await writeFile(
      resolve(metaDir, "artifact-map.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:tests/generated/createPost.test.ts",
            path: "tests/generated/createPost.test.ts",
            entity_ids: ["workflow:CreatePost"],
          },
        ],
      }),
    );
    await writeFile(
      resolve(metaDir, "ownership.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:tests/generated/createPost.test.ts",
            ownership_kind: "generated_file",
            write_scope: "whole_file",
            content_hash: sha256("ghost"),
          },
        ],
      }),
    );

    const report = await detectDrift(metaDir, projectRoot);
    expect(report.entries.length).toBe(1);
    const e = report.entries[0]!;
    expect(e.kind).toBe("missing_generated_test");
    expect(e.artifact_id).toBe("artifact:tests/generated/createPost.test.ts");
    expect(e.entity_ids).toEqual(["workflow:CreatePost"]);
  });

  it("returns no entries when on-disk bytes match the content_hash", async () => {
    const contents = "// generated by arch v1\n";
    const filePath = resolve(projectRoot, "src/generated/models/post.ts");
    await writeFileEnsuringDir(filePath, contents);

    await writeFile(
      resolve(metaDir, "artifact-map.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:src/generated/models/post.ts",
            path: "src/generated/models/post.ts",
            entity_ids: ["model:Post"],
          },
        ],
      }),
    );
    await writeFile(
      resolve(metaDir, "ownership.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:src/generated/models/post.ts",
            ownership_kind: "generated_file",
            write_scope: "whole_file",
            content_hash: sha256(contents),
          },
        ],
      }),
    );

    const report = await detectDrift(metaDir, projectRoot);
    expect(report.entries).toEqual([]);
  });

  it("ignores human-owned artifacts even if they exist with different bytes", async () => {
    const filePath = resolve(projectRoot, "src/custom/email-handler.ts");
    await writeFileEnsuringDir(filePath, "// totally different bytes\n");

    await writeFile(
      resolve(metaDir, "artifact-map.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:src/custom/email-handler.ts",
            path: "src/custom/email-handler.ts",
            entity_ids: ["custom:email"],
          },
        ],
      }),
    );
    await writeFile(
      resolve(metaDir, "ownership.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:src/custom/email-handler.ts",
            ownership_kind: "extension_point",
            write_scope: "stub_only",
            content_hash: sha256("stub-original"),
          },
        ],
      }),
    );

    const report = await detectDrift(metaDir, projectRoot);
    expect(report.entries).toEqual([]);
  });

  it("sorts entries deterministically by path", async () => {
    await writeFile(
      resolve(metaDir, "artifact-map.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:b",
            path: "src/generated/b.ts",
            entity_ids: [],
          },
          {
            artifact_id: "artifact:a",
            path: "src/generated/a.ts",
            entity_ids: [],
          },
        ],
      }),
    );
    await writeFile(
      resolve(metaDir, "ownership.json"),
      JSON.stringify({
        entries: [
          {
            artifact_id: "artifact:b",
            ownership_kind: "generated_file",
            write_scope: "whole_file",
            content_hash: sha256("missing"),
          },
          {
            artifact_id: "artifact:a",
            ownership_kind: "generated_file",
            write_scope: "whole_file",
            content_hash: sha256("missing"),
          },
        ],
      }),
    );

    const report = await detectDrift(metaDir, projectRoot);
    expect(report.entries.map((e) => e.path)).toEqual([
      "src/generated/a.ts",
      "src/generated/b.ts",
    ]);
  });
});
